### ISSUE TITLE
Add otm, mto, mtm from Doctrine

### ISSUE THREAD

**Issue by TomasVotruba** [TomasVotruba/PhpStorm-LiveTemplates#2]

**Comment by MaximStrutinskiy** [comment]
http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/association-mapping.html

**Comment by TomasVotruba** [comment]
@MaximStrutinskiy That's for reference to explain these shortcuts? Do you use this package?

**Comment by MaximStrutinskiy** [comment]
It's a Doctrine mapping.
otm - one to meny ;
mto - meny to one; 
mtm - many to many; 

For example:
`<?php
/** @Entity */
class Customer
{
    // ...

    /**
     * One Customer has One Cart.
     * @OneToOne(targetEntity="Cart", mappedBy="customer")
     */
    private $cart;

    // ...
}

/** @Entity */
class Cart
{
    // ...

    /**
     * One Cart has One Customer.
     * @OneToOne(targetEntity="Customer", inversedBy="cart")
     * @JoinColumn(name="customer_id", referencedColumnName="id")
     */
    private $customer;

    // ...
}`

**Comment by TomasVotruba** [comment]
Yes, it is.
